### ISSUE TITLE
Group chat application

### ISSUE THREAD

**Issue by shashankp10** [Developers-Adgitm/Projects#12]
## **Describe the project**
This is a group chat application using springboot, Javascript, HTML and CSS

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [✅] New Project

## **Screenshots**
![Screenshot 2023-08-29 130027](https://github.com/Developers-Adgitm/Projects/assets/102212264/67d8dc1e-6731-4099-95d4-789b00a80fc5)
![Screenshot 2023-08-29 130154](https://github.com/Developers-Adgitm/Projects/assets/102212264/b96ee05f-b221-43f9-8da6-36abd6d1e63c)

**Comment by Developers-Adgitm** [comment]
improve documentation

**Comment by Developers-Adgitm** [comment]
Go ahead , Create pull request after watching that video
