### ISSUE TITLE
new Project - downloadify

### ISSUE THREAD

**Issue by LakshayGMZ** [Developers-Adgitm/Projects#14]
## **Describe the project**
A web app that helps you download any youtube video with customizable download options.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [x] Documentation
- [x] New Project

## **Additional context**
hosted url: https://downloadify.vercel.app/
tech stacks: React, materialUI, flask, web scraping

## **Screenshots**
![image](https://imgur.com/p7GuwiX.png)
![image](https://imgur.com/whe1Irf.png)
- If applicable, add screenshots to help explain your problem.

**Comment by Developers-Adgitm** [comment]
Please upload the jpg image , not the link

**Comment by LakshayGMZ** [comment]
done

**Comment by Developers-Adgitm** [comment]
Great. You can now create the pull request.
