### ISSUE TITLE
E-learning website

### ISSUE THREAD

**Issue by Gunjanrathore8178** [Developers-Adgitm/Projects#15]
## **Describe the project**
This project acknowledges the students about the different courses which are free of cost, which save time ,efforts and money as well.

## Issue Type:

- [ ✔️] Documentation
- [ ✔️] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Developers-Adgitm** [comment]
Great , Create a pull request
