### ISSUE TITLE
Twitter_Sentiment_Analysis

### ISSUE THREAD

**Issue by tripti-bhardwaj** [Developers-Adgitm/Projects#17]
## **Describe the project**
Sentiment Analysis of a Twitter post using Logistic Regression.

## Issue Type:

- [ ✅] Documentation
- [✅ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Developers-Adgitm** [comment]
Go ahead Create pull request
