### ISSUE TITLE
New Project

### ISSUE THREAD

**Issue by mayank1784** [Developers-Adgitm/Projects#26]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [✅ ] Feature Request
- [✅ ] Documentation
- [ ✅] New Project

## **Additional context**
![Screenshot 2023-09-15 210955](https://github.com/Developers-Adgitm/Projects/assets/67159533/67526f0d-ab68-4289-9d1a-a6c12445ddcd)

Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Developers-Adgitm** [comment]
Go Ahead ! Create a Pull Request
