### ISSUE TITLE
E-commerce Backend

### ISSUE THREAD

**Issue by mayank1784** [Developers-Adgitm/Projects#29]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ✅] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by GDSC-DEVELOPERS** [comment]
Great , Open the pull request
