### ISSUE TITLE
Smart Scientific Calculator Using Python

### ISSUE THREAD

**Issue by palakbansal8810** [Developers-Adgitm/Projects#35]
## **Describe the project**
A Smart Scientific Calculator which also takes voice commands.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [✅ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by GDSC-DEVELOPERS** [comment]
Go ahead 
Open a Pull Request
