### ISSUE TITLE
NEW PROJECT REQUEST

### ISSUE THREAD

**Issue by codingwithveer18** [Developers-Adgitm/Projects#38]
## **Describe the project**
A mental Health awareness initiative
## Issue Type:
- [✅] New Project

## **Screenshots**
![Screenshot 2023-10-15 183234](https://github.com/Developers-Adgitm/Projects/assets/112725639/38a6e71b-76c7-4395-a683-aa85645753ce)

**Comment by GDSC-DEVELOPERS** [comment]
Good
Open the pull Request

**Comment by codingwithveer18** [comment]
Sure Sir
