### ISSUE TITLE
 Dice Game 

### ISSUE THREAD

**Issue by sakettt07** [Developers-Adgitm/Projects#44]
## **Describe the project**
Created a dice game using React js 

## Issue Type:

- [ ✅] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

![image](https://github.com/Developers-Adgitm/Projects/assets/127855345/e1c163e6-2535-45d1-91be-80c4022b0cef)

**Comment by sakettt07** [comment]
Can you please assign me this issue

**Comment by GDSC-DEVELOPERS** [comment]
Okay . Go ahead , Create a Pull Request
