### ISSUE TITLE
Fidget-Spinner

### ISSUE THREAD

**Issue by KhushalVashisth** [Developers-Adgitm/Projects#49]
## **Describe the project**
Stress Buster project.

## Issue Type:

- [✅] New Project

## **Screenshots**

![image](https://github.com/Developers-Adgitm/Projects/assets/139761210/af046c26-12d0-42ae-a864-24bdd416bd6e)

**Comment by GDSC-DEVELOPERS** [comment]
Go ahead , Create a Pull request
