### ISSUE TITLE
Dice-Game

### ISSUE THREAD

**Issue by sakettt07** [Developers-Adgitm/Projects#53]
## **Describe the project**
Made a Dice Game in ReactJs and used Styled Components

## Issue Type:

- [ ✅] New Project

## **Screenshots**

![image](https://github.com/Developers-Adgitm/Projects/assets/127855345/c9e7759b-a131-4204-a97a-221620bdf55e)

**Comment by GDSC-DEVELOPERS** [comment]
Go Ahead , Create Pull request
