### ISSUE TITLE
FoodoFest-Landing-Page

### ISSUE THREAD

**Issue by salonirai1807** [Developers-Adgitm/Projects#55]
## **Describe the project**
This is a landing Page resembling to a food ordering website.

## Issue Type:

- [ ✅] New Project

## **Screenshots**

![image](https://github.com/Developers-Adgitm/Projects/assets/127751130/5d4c085e-364a-4719-9a97-0a295fe95231)

**Comment by GDSC-DEVELOPERS** [comment]
Go Ahead , Create Pull request
