### ISSUE TITLE
Minimal Flutter rhyme app

### ISSUE THREAD

**Issue by Lauel09** [Developers-Adgitm/Projects#56]
## **Describe the project**
A minimal rhyming app written in Flutter, which uses GET/POST to get required rhymes from RhymeZone.

## Issue Type:

- [ ] Feature Request
- [ ] Documentation
- [✅ ] New Project

## **Screenshots**
Screenshot of the app:-
![image](https://github.com/Developers-Adgitm/Projects/assets/19989996/31cf3310-c702-4872-887e-82f1702c06e1)

##
I was also wondering, while my project is already uploaded to Github at my repo here: https://github.com/Lauel09/flutter-rhyme, is the standard process, the one where I fork the repo, move my code into it, and put up a PR, or my github repo could be directly linked within this master repo, as I have seen in other projects.
Thank you!

**Comment by GDSC-DEVELOPERS** [comment]
Open source contributions require some standard that to be followed.

**Comment by GDSC-DEVELOPERS** [comment]
Improve this project
