### ISSUE TITLE
New Project

### ISSUE THREAD

**Issue by codingwithveer18** [Developers-Adgitm/Projects#8]
## **Describe the project**
A clear and concise description of the project you are going to add to this repository.

## Issue Type:

- [✅] Feature Request
- [✅ ] Documentation
- [✅ ] New Project

## **Additional context**
Add any other context or screenshots about the project here.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Developers-Adgitm** [comment]
Improve documentation

**Comment by codingwithveer18** [comment]
Okay

**Comment by codingwithveer18** [comment]
Improved
